// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/apps": {
            "get": {
                "description": "List every AI application in the catalog with its runtime, model and accelerator requirement",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[App] AI Application Catalog"
                ],
                "summary": "List registered AI applications",
                "operationId": "GetAllApps",
                "responses": {
                    "200": {
                        "description": "AI application list",
                        "schema": {
                            "$ref": "#/definitions/model.AppSpecListResp"
                        }
                    }
                }
            },
            "post": {
                "description": "Register or replace an AI application metadata record. Replacing an existing id publishes a new version",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[App] AI Application Catalog"
                ],
                "summary": "Register an AI application",
                "operationId": "PostApp",
                "parameters": [
                    {
                        "description": "AI application metadata",
                        "name": "appSpec",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AppSpec"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "AI application registered",
                        "schema": {
                            "$ref": "#/definitions/model.AppSpec"
                        }
                    },
                    "400": {
                        "description": "Malformed or incomplete metadata",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/apps/{appId}": {
            "get": {
                "description": "Read one registered AI application, including its install commands and serving port",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[App] AI Application Catalog"
                ],
                "summary": "Get an AI application",
                "operationId": "GetApp",
                "parameters": [
                    {
                        "type": "string",
                        "default": "vllm-llama31-8b",
                        "description": "AI application ID",
                        "name": "appId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "AI application metadata",
                        "schema": {
                            "$ref": "#/definitions/model.AppSpec"
                        }
                    },
                    "404": {
                        "description": "AI application not found",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove an AI application from the catalog. Deployments already running are untouched",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[App] AI Application Catalog"
                ],
                "summary": "Delete an AI application",
                "operationId": "DeleteApp",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AI application ID",
                        "name": "appId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "AI application deleted",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "404": {
                        "description": "AI application not found",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/apps/{appId}/specs": {
            "get": {
                "description": "Find node specs across every connected cloud that satisfy the accelerator requirement, cheapest first",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[App] AI Application Catalog"
                ],
                "summary": "Recommend accelerator specs for an AI application",
                "operationId": "GetAppSpecs",
                "parameters": [
                    {
                        "type": "string",
                        "default": "vllm-llama31-8b",
                        "description": "AI application ID",
                        "name": "appId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "How many candidates to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Matching node specs",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.SpecCandidate"
                            }
                        }
                    },
                    "404": {
                        "description": "AI application not found",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Spec recommendation failed",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/archive": {
            "get": {
                "description": "List archived deployment and control runs, newest first. A record holds the instruction, every tool call with its arguments and the guard verdict",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Archive] Deploy and Control Archive"
                ],
                "summary": "List archived runs",
                "operationId": "GetArchive",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "How many records to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Archived runs",
                        "schema": {
                            "$ref": "#/definitions/model.ArchiveListResp"
                        }
                    },
                    "400": {
                        "description": "Malformed limit",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Archive lookup failed",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/archive/{runId}": {
            "get": {
                "description": "Read one archived run by its identifier",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Archive] Deploy and Control Archive"
                ],
                "summary": "Get one archived run",
                "operationId": "GetArchiveRun",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Run ID",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Archived run",
                        "schema": {
                            "$ref": "#/definitions/model.ArchiveRecord"
                        }
                    },
                    "404": {
                        "description": "Run not found",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Archive lookup failed",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/ns/{nsId}/deployments": {
            "get": {
                "description": "List every deployment of the namespace with its node status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Deploy] AI Application Deployment"
                ],
                "summary": "List deployments",
                "operationId": "GetAllDeployments",
                "parameters": [
                    {
                        "type": "string",
                        "default": "default",
                        "description": "Namespace ID",
                        "name": "nsId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deployment list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tumblebug.InfraInfo"
                            }
                        }
                    },
                    "500": {
                        "description": "Deployment lookup failed",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    }
                }
            },
            "post": {
                "description": "Provision nodes and install the AI application on them. The request is reviewed first, refused if the name is taken, and only sent to the cloud when the dry-run guard is off",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Deploy] AI Application Deployment"
                ],
                "summary": "Deploy an AI application",
                "operationId": "PostDeployment",
                "parameters": [
                    {
                        "type": "string",
                        "default": "default",
                        "description": "Namespace ID",
                        "name": "nsId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Deployment request",
                        "name": "deployReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DeployAppReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deployment planned or provisioned",
                        "schema": {
                            "$ref": "#/definitions/model.DeploymentResult"
                        }
                    },
                    "400": {
                        "description": "Malformed request or request not viable",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "404": {
                        "description": "AI application not found",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "409": {
                        "description": "Deployment name already in use",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Deployment failed",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/ns/{nsId}/deployments/plan": {
            "post": {
                "description": "Build the provisioning request for an AI application without contacting any cloud. Leave specId empty to select the cheapest spec matching the accelerator requirement",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Deploy] AI Application Deployment"
                ],
                "summary": "Plan a deployment",
                "operationId": "PostDeploymentPlan",
                "parameters": [
                    {
                        "type": "string",
                        "default": "default",
                        "description": "Namespace ID",
                        "name": "nsId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Deployment request",
                        "name": "deployReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DeployAppReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deployment plan",
                        "schema": {
                            "$ref": "#/definitions/model.DeploymentPlan"
                        }
                    },
                    "400": {
                        "description": "Malformed or incomplete request",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "404": {
                        "description": "AI application not found",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Deployment planning failed",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/ns/{nsId}/deployments/{infraId}": {
            "delete": {
                "description": "Terminate every node of the deployment and remove its records. Shared resources of the namespace are kept",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Deploy] AI Application Deployment"
                ],
                "summary": "Delete a deployment",
                "operationId": "DeleteDeployment",
                "parameters": [
                    {
                        "type": "string",
                        "default": "default",
                        "description": "Namespace ID",
                        "name": "nsId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Deployment ID",
                        "name": "infraId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deployment deleted or planned",
                        "schema": {
                            "$ref": "#/definitions/model.ControlResult"
                        }
                    },
                    "404": {
                        "description": "Deployment not found",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Deployment deletion failed",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/ns/{nsId}/deployments/{infraId}/control": {
            "post": {
                "description": "Apply suspend, resume, reboot or terminate to every node. terminate stops the nodes but keeps the records, so delete afterwards to stop billing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Deploy] AI Application Deployment"
                ],
                "summary": "Control a deployment",
                "operationId": "PostDeploymentControl",
                "parameters": [
                    {
                        "type": "string",
                        "default": "default",
                        "description": "Namespace ID",
                        "name": "nsId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Deployment ID",
                        "name": "infraId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Lifecycle action",
                        "name": "controlReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ControlAppReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Action applied or planned",
                        "schema": {
                            "$ref": "#/definitions/model.ControlResult"
                        }
                    },
                    "400": {
                        "description": "Unsupported action",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "404": {
                        "description": "Deployment not found",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Deployment control failed",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/ns/{nsId}/deployments/{infraId}/status": {
            "get": {
                "description": "Report the node status summary, suitable for polling while a deployment comes up",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Deploy] AI Application Deployment"
                ],
                "summary": "Get deployment status",
                "operationId": "GetDeploymentStatus",
                "parameters": [
                    {
                        "type": "string",
                        "default": "default",
                        "description": "Namespace ID",
                        "name": "nsId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Deployment ID",
                        "name": "infraId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deployment status",
                        "schema": {
                            "$ref": "#/definitions/tumblebug.InfraStatusView"
                        }
                    },
                    "404": {
                        "description": "Deployment not found",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Deployment status lookup failed",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/ns/{nsId}/intents": {
            "post": {
                "description": "Hand an operator instruction to the deployment agent. The agent resolves the application, recommends an accelerator spec, reviews the request and, when the dry-run guard is off, provisions. Every step is archived",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Agent] AI Application Automation Agent"
                ],
                "summary": "Run a natural language deployment intent",
                "operationId": "PostIntent",
                "parameters": [
                    {
                        "type": "string",
                        "default": "default",
                        "description": "Namespace ID",
                        "name": "nsId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Operator instruction",
                        "name": "intentReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.IntentReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Agent run finished",
                        "schema": {
                            "$ref": "#/definitions/model.IntentResp"
                        }
                    },
                    "400": {
                        "description": "Malformed or empty instruction",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Agent run failed",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "503": {
                        "description": "Planning model is not configured",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Report whether the service finished initialization and can accept requests",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Health] Service Health"
                ],
                "summary": "Check service readiness",
                "operationId": "GetReadyz",
                "responses": {
                    "200": {
                        "description": "Service is ready",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "503": {
                        "description": "Service is still initializing",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/tools": {
            "get": {
                "description": "List every tool the agent may call, with its risk grade and whether the dry-run guard applies. Exposed so another agent framework can adopt the same tool surface",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Agent] AI Application Automation Agent"
                ],
                "summary": "List agent tools",
                "operationId": "GetTools",
                "responses": {
                    "200": {
                        "description": "Tool catalog",
                        "schema": {
                            "$ref": "#/definitions/model.ToolListResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AcceleratorRequirement": {
            "type": "object",
            "required": [
                "minCount",
                "type"
            ],
            "properties": {
                "minCount": {
                    "description": "MinCount is the smallest acceptable number of devices per node.",
                    "type": "integer",
                    "example": 1
                },
                "minMemoryGiB": {
                    "description": "MinMemoryGiB is the smallest acceptable per-device memory. Zero means unset.",
                    "type": "number",
                    "example": 22
                },
                "model": {
                    "description": "Model narrows the search to a device model. Empty means any model of Type.",
                    "type": "string",
                    "example": "NVIDIA L4"
                },
                "type": {
                    "description": "Type is the accelerator class, matched against the spec acceleratorType.",
                    "type": "string",
                    "example": "gpu"
                }
            }
        },
        "model.AppSpec": {
            "type": "object",
            "required": [
                "accelerator",
                "id",
                "install",
                "model",
                "name",
                "runtime",
                "serving",
                "version"
            ],
            "properties": {
                "accelerator": {
                    "$ref": "#/definitions/model.AcceleratorRequirement"
                },
                "deployTargets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.DeployTarget"
                    }
                },
                "description": {
                    "type": "string",
                    "example": "OpenAI compatible inference endpoint"
                },
                "id": {
                    "type": "string",
                    "example": "vllm-llama31-8b"
                },
                "install": {
                    "$ref": "#/definitions/model.InstallSpec"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "model": {
                    "$ref": "#/definitions/model.ModelRef"
                },
                "name": {
                    "type": "string",
                    "example": "vLLM Llama 3.1 8B Instruct"
                },
                "resources": {
                    "$ref": "#/definitions/model.ResourceRequirement"
                },
                "runtime": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Runtime"
                        }
                    ],
                    "example": "vllm"
                },
                "runtimeVersion": {
                    "type": "string",
                    "example": "0.6.3"
                },
                "serving": {
                    "$ref": "#/definitions/model.ServingSpec"
                },
                "version": {
                    "type": "string",
                    "example": "0.1.0"
                }
            }
        },
        "model.AppSpecListResp": {
            "type": "object",
            "properties": {
                "apps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.AppSpec"
                    }
                }
            }
        },
        "model.ArchiveListResp": {
            "type": "object",
            "properties": {
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ArchiveRecord"
                    }
                }
            }
        },
        "model.ArchiveRecord": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "endedAt": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "intent": {
                    "type": "string"
                },
                "kind": {
                    "type": "string",
                    "example": "intent"
                },
                "nsId": {
                    "type": "string"
                },
                "runId": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ToolStep"
                    }
                },
                "usage": {
                    "$ref": "#/definitions/model.TokenUsage"
                }
            }
        },
        "model.ControlAppReq": {
            "type": "object",
            "required": [
                "action"
            ],
            "properties": {
                "action": {
                    "description": "Action is one of suspend, resume, reboot, terminate.",
                    "type": "string",
                    "enum": [
                        "suspend",
                        "resume",
                        "reboot",
                        "terminate"
                    ],
                    "example": "suspend"
                }
            }
        },
        "model.ControlResult": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "affected": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dryRun": {
                    "type": "boolean"
                },
                "infraId": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "model.DeployAppReq": {
            "type": "object",
            "required": [
                "appId",
                "infraName"
            ],
            "properties": {
                "appId": {
                    "description": "AppID selects the registered application to deploy.",
                    "type": "string",
                    "example": "vllm-llama31-8b"
                },
                "imageId": {
                    "description": "ImageID pins the node image. Empty asks CB-Tumblebug to select one.",
                    "type": "string",
                    "example": "ubuntu22.04"
                },
                "infraName": {
                    "description": "InfraName becomes the CB-Tumblebug Infra ID and is the idempotency key.",
                    "type": "string",
                    "example": "vllm-lab-01"
                },
                "nodeCount": {
                    "description": "NodeCount is how many serving nodes to provision.",
                    "type": "integer",
                    "example": 1
                },
                "specId": {
                    "description": "SpecID pins the node spec. Empty asks for a recommendation first.",
                    "type": "string",
                    "example": "aws+us-west-2+g6.xlarge"
                }
            }
        },
        "model.DeployTarget": {
            "type": "string",
            "enum": [
                "vm",
                "container"
            ],
            "x-enum-varnames": [
                "DeployTargetVM",
                "DeployTargetContainer"
            ]
        },
        "model.DeploymentPlan": {
            "type": "object",
            "properties": {
                "acceleratorSummary": {
                    "description": "AcceleratorSummary describes the accelerator the chosen spec provides.",
                    "type": "string"
                },
                "appId": {
                    "type": "string"
                },
                "appName": {
                    "type": "string"
                },
                "estimatedCost": {
                    "description": "EstimatedCost is the CB-Tumblebug review estimate, when a review ran.",
                    "type": "string"
                },
                "imageId": {
                    "type": "string"
                },
                "imageReason": {
                    "description": "ImageReason explains an image that was resolved rather than requested.",
                    "type": "string"
                },
                "imageSource": {
                    "description": "ImageSource records how ImageID was chosen: \"requested\" or \"resolved\".",
                    "type": "string"
                },
                "infraName": {
                    "type": "string"
                },
                "nodeCount": {
                    "type": "integer"
                },
                "nsId": {
                    "type": "string"
                },
                "request": {
                    "description": "Request is the dynamic Infra request body, including the install commands."
                },
                "specId": {
                    "type": "string"
                },
                "specSource": {
                    "description": "SpecSource records how SpecID was chosen: \"requested\" or \"recommended\".",
                    "type": "string"
                }
            }
        },
        "model.DeploymentResult": {
            "type": "object",
            "properties": {
                "dryRun": {
                    "description": "DryRun is true when the plan was archived but never sent.",
                    "type": "boolean"
                },
                "infra": {
                    "description": "Infra is the provisioned Infra, present only on a real run."
                },
                "message": {
                    "description": "Message explains the outcome to the caller.",
                    "type": "string"
                },
                "plan": {
                    "$ref": "#/definitions/model.DeploymentPlan"
                },
                "review": {
                    "description": "Review is the CB-Tumblebug pre-flight verdict, when a review ran.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.ReviewSummary"
                        }
                    ]
                }
            }
        },
        "model.InstallSpec": {
            "type": "object",
            "required": [
                "commands"
            ],
            "properties": {
                "commands": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "osType": {
                    "description": "OSType selects the node image family. Empty uses the service default.",
                    "type": "string",
                    "example": "ubuntu 22.04"
                },
                "timeoutMinutes": {
                    "type": "integer",
                    "example": 30
                },
                "userName": {
                    "type": "string",
                    "example": "cb-user"
                }
            }
        },
        "model.IntentReq": {
            "type": "object",
            "required": [
                "intent"
            ],
            "properties": {
                "intent": {
                    "description": "Intent is what the operator wants, in their own words.",
                    "type": "string",
                    "example": "Llama 3.1 8B 추론 서버를 GPU 한 장짜리 노드에 올려줘"
                }
            }
        },
        "model.IntentResp": {
            "type": "object",
            "properties": {
                "answer": {
                    "description": "Answer is what the agent reports back to the operator.",
                    "type": "string"
                },
                "dryRun": {
                    "description": "DryRun reflects the guard setting the run executed under.",
                    "type": "boolean"
                },
                "runId": {
                    "type": "string"
                },
                "steps": {
                    "description": "Steps is every tool the agent chose, in order, with what the guard did.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ToolStep"
                    }
                },
                "usage": {
                    "$ref": "#/definitions/model.TokenUsage"
                }
            }
        },
        "model.ModelRef": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "format": {
                    "description": "Format is the artifact format the runtime loads.",
                    "type": "string",
                    "example": "safetensors"
                },
                "id": {
                    "description": "ID is the model identifier in the AI model registry.",
                    "type": "string",
                    "example": "meta-llama/Llama-3.1-8B-Instruct"
                },
                "sizeGiB": {
                    "description": "SizeGiB is the on-disk footprint, used to size the root disk.",
                    "type": "number",
                    "example": 16
                }
            }
        },
        "model.ResourceRequirement": {
            "type": "object",
            "properties": {
                "minMemoryGiB": {
                    "type": "integer",
                    "example": 32
                },
                "minVCPU": {
                    "type": "integer",
                    "example": 8
                },
                "rootDiskGiB": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "model.ReviewSummary": {
            "type": "object",
            "properties": {
                "creationViable": {
                    "type": "boolean"
                },
                "estimatedCost": {
                    "type": "string"
                },
                "overallMessage": {
                    "type": "string"
                },
                "overallStatus": {
                    "type": "string"
                },
                "recommendations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "totalNodeCount": {
                    "type": "integer"
                }
            }
        },
        "model.Runtime": {
            "type": "string",
            "enum": [
                "vllm",
                "triton",
                "tgi",
                "ollama"
            ],
            "x-enum-varnames": [
                "RuntimeVLLM",
                "RuntimeTriton",
                "RuntimeTGI",
                "RuntimeOllama"
            ]
        },
        "model.ServingSpec": {
            "type": "object",
            "required": [
                "port"
            ],
            "properties": {
                "healthPath": {
                    "type": "string",
                    "example": "/health"
                },
                "port": {
                    "type": "integer",
                    "example": 8000
                },
                "protocol": {
                    "type": "string",
                    "example": "http"
                }
            }
        },
        "model.SimpleMsg": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "AI application not found"
                }
            }
        },
        "model.SpecCandidate": {
            "type": "object",
            "properties": {
                "acceleratorCount": {
                    "type": "integer"
                },
                "acceleratorMemoryGB": {
                    "type": "number"
                },
                "acceleratorModel": {
                    "type": "string"
                },
                "acceleratorType": {
                    "type": "string"
                },
                "costPerHour": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "memoryGiB": {
                    "type": "number"
                },
                "providerName": {
                    "type": "string"
                },
                "regionName": {
                    "type": "string"
                },
                "vCPU": {
                    "type": "integer"
                }
            }
        },
        "model.TokenUsage": {
            "type": "object",
            "properties": {
                "inputTokens": {
                    "type": "integer"
                },
                "outputTokens": {
                    "type": "integer"
                }
            }
        },
        "model.ToolDescriptor": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "grade": {
                    "description": "Grade is one of read, review, write, destructive.",
                    "type": "string"
                },
                "guardedByDryRun": {
                    "description": "GuardedByDryRun is true when the dry-run setting can block this tool.",
                    "type": "boolean"
                },
                "inputSchema": {},
                "name": {
                    "type": "string"
                }
            }
        },
        "model.ToolListResp": {
            "type": "object",
            "properties": {
                "dryRun": {
                    "type": "boolean"
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ToolDescriptor"
                    }
                }
            }
        },
        "model.ToolStep": {
            "type": "object",
            "properties": {
                "calledAt": {
                    "type": "string"
                },
                "duration": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "executed": {
                    "description": "Executed is false when the dry-run guard blocked an infrastructure change.",
                    "type": "boolean"
                },
                "grade": {
                    "description": "Grade is the tool risk grade that decided whether the call was executed.",
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "input": {},
                "output": {},
                "tool": {
                    "type": "string"
                }
            }
        },
        "tumblebug.InfraInfo": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "node": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tumblebug.NodeInfo"
                    }
                },
                "status": {
                    "type": "string"
                },
                "statusCount": {
                    "$ref": "#/definitions/tumblebug.StatusCountInfo"
                },
                "targetStatus": {
                    "type": "string"
                }
            }
        },
        "tumblebug.InfraStatusView": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "statusCount": {
                    "$ref": "#/definitions/tumblebug.StatusCountInfo"
                },
                "targetAction": {
                    "type": "string"
                },
                "targetStatus": {
                    "type": "string"
                }
            }
        },
        "tumblebug.NodeInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "imageId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nodeGroupId": {
                    "type": "string"
                },
                "privateIP": {
                    "type": "string"
                },
                "publicIP": {
                    "type": "string"
                },
                "specId": {
                    "type": "string"
                },
                "sshPort": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "tumblebug.StatusCountInfo": {
            "type": "object",
            "properties": {
                "countCreating": {
                    "type": "integer"
                },
                "countFailed": {
                    "type": "integer"
                },
                "countRunning": {
                    "type": "integer"
                },
                "countSuspended": {
                    "type": "integer"
                },
                "countTerminated": {
                    "type": "integer"
                },
                "countTotal": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/aiapp",
	Schemes:          []string{},
	Title:            "AI-MCMP AI Application Automation Agent (Prototype)",
	Description:      "Registers AI application metadata, turns an operator instruction into CB-Tumblebug calls through an LLM, deploys the application onto AI semiconductor nodes and archives every step.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
